[phases.setup]
nixPkgs = [
    "python3",
    "pango",
    "gobject-introspection",
    "cairo",
    "gdk-pixbuf"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"