# nixpacks.toml

[phases.setup]
nixPkgs = [
    "python3",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "glib",                   # <--- INI PERBAIKANNYA (untuk libgobject)
    "gobject-introspection",
    "harfbuzz",
    "librsvg",                # Tambahan untuk grafis
    "dejavu_fonts"            # Wajib untuk font PDF
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"